### ISSUE TITLE
Update HCSC Launch Plan

### ISSUE THREAD

**Issue by thierrychau** [DPI-WE/curriculum#52]
@heratyian 

A day in the life of:
- A bit humoristic, TDD [Learn with Phil](https://www.youtube.com/watch?v=aCP4tDSpjGQ)
- Fixing tickets [ProCoder](https://www.youtube.com/watch?v=eBWm1l1AZF8)

What do you think of moving "Eloquent JavaScript" to books, or did you want it to be highlighted better within courses?
What do you think of adding the intro to JS from Scrimba in the courses?

**Comment by heratyian** [comment]
sounds good. it might also be good to add this book https://martinfowler.com/books/eaa.html

hcsc strongly insists on learning Java, but I still think some javascript is essential.
